# generated by datamodel-codegen:
#   filename:  openai_credentials_schema.json
#   timestamp: 2024-12-30T17:58:57+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class OpenAICredentials(BaseModel):
    api_key: str = Field(..., description='The API key for the OpenAI API')
    model_id: str = Field(..., description='The ID of the OpenAI model to use')
