# generated by datamodel-codegen:
#   filename:  agent_info_schema.json
#   timestamp: 2024-12-30T16:41:44+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class AgentInfo(BaseModel):
    name: str = Field(..., description='The name of the agent')
    active_subreddit: str = Field(
        ..., description='The subreddit the agent is active in. Exclude the r/ prefix.'
    )
